package ar.edu.unlam.pb2.educacion;

public enum Competencias {
    MAESTRX_JARDINERX, MAESTRX, PRIMERO, SEGUNDO, TERCERO, CUARTO, QUINTO, SEXTO, MATERIA_1, MATERIA_2, MATERIA_3, MATERIA_4, MATERIA_5, MATERIA_6, MATERIA_7
}
